---
title: "Camaros on eBay!: Initial Exploration"
author: "Curtis L. Hampton"
date: "August 21, 2017"
output: html_notebook
---

```{r message=FALSE}
library(RPostgreSQL)
library(lubridate)
library(ggplot2)
```

```{r results='hide'}
# connect to the database
con <- dbConnect(dbDriver("PostgreSQL"), 
                 dbname = "postgres",
                 host = "localhost", 
                 port = 5432,
                 user = "postgres", 
                 password = "apassword")

# make sure the table exists
dbExistsTable(con, "ebay_merged")

# only look at cars with a clear title
query = "SELECT * 
         FROM ebay_merged 
         WHERE year >= 2016 
           AND year <= 2018
           AND title = 'clear'"

# store query results in a dataframe
df_all <- dbGetQuery(con, query)

# disconnect from the database
dbDisconnect(con)
```

```{r}
# inspect the structure of data
str(df_all)
```

```{r}
# subset the df to only inlucde the columns of interest
df  <-  df_all[, c('itemid', 
                   'price', 
                   'year', 
                   'mileage', 
                   'condition', 
                   'cyl', 
                   'trans', 
                   'status', 
                   'endtime')]
```

```{r}
# change status to 1/0, where 1 = EndedWithSales
df$status <- ifelse(df$status == 'EndedWithSales', 1, 0)
```

```{r}
# set variables type accordingly
df$price <-  as.numeric(df$price)
df$year <- as.factor(df$year)
df$condition <- factor(df$condition, levels=c("Used", "Certified pre-owned", "New"), ordered=FALSE)
df$cyl <- as.factor(df$cyl)
df$trans <- as.factor(df$trans)
df$status <- as.factor(df$status)
df$MONTH <- factor(month(df$endtime, label = TRUE))
df$WEEKDAY <- factor(wday(df$endtime, label = TRUE))
df$HOUR <- factor(hour(df$endtime))
df$endtime <- NULL
```

```{r}
# create variable names for status
levels(df$year) <- make.names(levels(factor(df$year)))
levels(df$condition) <- make.names(levels(factor(df$condition)))
levels(df$cyl) <- make.names(levels(factor(df$cyl)))
levels(df$trans) <- make.names(levels(factor(df$trans)))
levels(df$status) <- make.names(c("notSold", "sold"))
```

```{r}
# drop records that contain a NA anywhere
df <- df[complete.cases(df),]
```



```{r}
# show sample of dataframe
head(df)
```

```{r}
# plot differences in number of auctions by vehicle year
ggplot(data = df, mapping = aes(x = year)) +
    geom_bar(aes(fill = year)) +
    geom_text(stat = 'count', mapping = aes(label = ..count..), vjust = -0.5) +
    ggtitle("Number of Auctions by Vehicle Year") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```



```{r}
# plot differences in ending price for not sold vs sold
ggplot(data = df) +
    geom_boxplot(mapping = aes(x = status, y = price, fill = status)) +
    ggtitle("Final Price by Selling Status") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# show summary statistics for each group
tapply(df$price, df$status, summary)
```

```{r}
# make ranges comparable by removing ads of cars that didn't sell outside range of cars that did sell
min_sold <- min(df[df$status == "sold", ]['price'])
max_sold <- max(df[df$status == "sold", ]['price'])
df <- df[min_sold <= df$price & df$price <= max_sold, ]
```

```{r}
# plot differences in ending price for sold vs not sold
ggplot(data = df) +
    geom_boxplot(mapping = aes(x = status, y = price, fill = status)) + 
    ggtitle("Final Price of Cars by Selling Status (excluding outliers)") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# plot the number of cars that did not sell compared to the number that did sell
ggplot(data = df, mapping = aes(x = status)) +
    geom_bar(aes(fill = status)) +
    geom_text(stat = 'count', mapping = aes(label = ..count..), vjust = -0.5) +
    ggtitle("Number of Cars by Selling Status (excluding outliers)") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# plot the auctions by month
ggplot(data = df, mapping = aes(x = MONTH)) +
    geom_bar(aes(fill = MONTH)) +
    geom_text(stat = 'count', mapping = aes(label = ..count..), vjust = -0.5) +
    ggtitle("Number of Auctions on Month (excluding outliers)") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# remove the 5 auctions in ended as March
df <- df[df$MONTH != "Mar", ]
```

```{r}
# plot the auctions by weekday
ggplot(data = df, mapping = aes(x = WEEKDAY)) +
    geom_bar(aes(fill = WEEKDAY)) +
    geom_text(stat = 'count', mapping = aes(label = ..count..), vjust = -0.5) +
    ggtitle("Number of Auctions Ending on Weekday (excluding outliers)") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# plot the auctions by hour of day
ggplot(data = df, mapping = aes(x = HOUR)) +
    geom_bar(aes(fill = HOUR)) +
    geom_text(stat = 'count', mapping = aes(label = ..count..), vjust = -0.5) +
    ggtitle("Number of Auctions Ending on Hour of Day (excluding outliers)") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# plot the proportion of cars that sold per weekday
ggplot(data = df) +
    geom_bar(mapping = aes(x = WEEKDAY, fill = status), position = 'fill') +
    ggtitle("Number of Cars Sold by Weekday (excluding outliers)") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# plot the proportion of cars that sold per month
ggplot(data = df) +
    geom_bar(mapping = aes(x = MONTH, fill = status), position = 'fill') +
    ggtitle("Number of Cars Sold by Month (excluding outliers)") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# plot the proportion of cars that sold per month
ggplot(data = df) +
    geom_bar(mapping = aes(x = year, fill = status), position = 'fill') +
    ggtitle("Number of Cars Sold by Year (excluding outliers)") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# connect to the database
con <- dbConnect(dbDriver("PostgreSQL"), 
                 dbname = "postgres",
                 host = "localhost", 
                 port = 5432,
                 user = "postgres", 
                 password = "apassword")

# write new table to database
dbWriteTable(con, "ebay_6gen", df, overwrite=TRUE)

# disconnect from the database
dbDisconnect(con)
```
