---
title: "Camaros on eBay!: Predicting Selling Price"
author: "Curtis L. Hampton"
date: "August 21, 2017"
output: html_notebook
---

```{r message=FALSE}
library(RPostgreSQL)
library(lubridate)
library(ggplot2)
library(GGally)
library(car)
```

```{r results='hide'}
# connect to the database and load the merged data
con <- dbConnect(dbDriver("PostgreSQL"), 
                 dbname = "postgres",
                 host = "localhost", 
                 port = 5432,
                 user = "postgres", 
                 password = "apassword")

# only look at cars with a clear title
query = "SELECT * 
         FROM ebay_merged 
         WHERE title = 'clear'
           AND year BETWEEN 2016 AND 2018
           AND status = 'EndedWithSales'"

# store the query results in a dataframe
df_all <- dbGetQuery(con, query)

# disconnect from the database
dbDisconnect(con)
```

```{r}
# inspect the structure of data
str(df_all)
```

```{r}
# subset the df to only inlucde the columns of interest
df  <-  df_all[, c('itemid', 
                   'price', 
                   'year', 
                   'mileage', 
                   'condition', 
                   'cyl', 
                   'trans',
                   'trim')]
```

```{r}
# set variables type accordingly
df$price <-  as.numeric(df$price)
df$year <- as.factor(df$year)
df$condition <- factor(df$condition, levels=c("Used", "New"), ordered=FALSE)
df$cyl <- as.factor(df$cyl)
df$trans <- as.factor(df$trans)
df$trim <- as.factor(df$trim)
```

```{r}
# create variable names for status
levels(df$year) <- make.names(levels(factor(df$year)))
levels(df$condition) <- make.names(levels(factor(df$condition)))
levels(df$cyl) <- make.names(levels(factor(df$cyl)))
levels(df$trans) <- make.names(levels(factor(df$trans)))
```

```{r}
# drop records that contain a NA anywhere
df <- df[complete.cases(df),]
```

```{r}
# plot the selling price of the cars
ggplot(data = df, aes(x=price)) + 
    geom_histogram(aes(fill = ..count..), bins = 20) + 
    theme(legend.position = "right") + 
    ggtitle("Count of Selling Price") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# plot the selling price of a car by the year
ggplot(data = df, mapping = aes(x = year, y = price)) + 
    geom_boxplot(mapping = aes(fill = year)) +
    theme(legend.position = "right") +
    ggtitle("Selling Price by Year") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```


```{r}
# plot the selling price of a car by the year
ggplot(data = df, mapping = aes(x = trim, y = price)) + 
    geom_boxplot(mapping = aes(fill = trim)) +
    theme(legend.position = "right") +
    ggtitle("Selling Price by Trim") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```


```{r}
# plot the selling price of a car by the mileage, while also considering number of cylinders
ggplot(data = df, mapping = aes(x = mileage, y = price)) + 
    geom_point(mapping = aes(color = cyl)) +
    theme(legend.position = "right") +
    ggtitle("Selling Price vs. Mileage") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```


```{r}
# look for differences in price according to number of cylinders
ggplot(data = df, mapping = aes(x = cyl, y = price)) +
    geom_boxplot(mapping = aes(fill = cyl)) + 
    theme(legend.position = "right") +
    ggtitle("Final Price by Number of Cylinders") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# look for differences in price according to transmission type
ggplot(data = df, mapping = aes(x = trans, y = price)) +
    geom_boxplot(mapping = aes(fill = trans)) + 
    theme(legend.position = "right") +
    ggtitle("Selling Price by Transmission Type") + 
    theme(plot.title = element_text(lineheight=.8, face="bold", hjust = 0.5))
```

```{r}
# what variables are available?
names(df)
```

```{r}
# create initail regression model with all variables
fit <- lm(price ~ year + mileage + cyl + trans + condition, 
          data=df, 
          na.action = na.exclude)
```

```{r}
# check for multi-collinearity
vif(fit)
```

```{r}
# show the results of the model
summary(fit)
```

```{r}
# join results with df
results <- cbind(pred = predict(fit), resid = resid(fit), std_resid = rstandard(fit), df)
```

```{r}
# plot the model fit
plot(fit)
```

```{r}
# look for observations with high leverage
cutoff <- 4/((nrow(df)-length(fit$coefficients)-2))
plot(fit, which=4, cook.levels=cutoff)
```

```{r}
# what's the deal with these outliers...
results[c(2, 10, 20),]
```

```{r}
# sort results by residual value
results <- results[order(results$resid), ]
head(results, n=10)
```

```{r}
# plot residual for each year
ggplot(data = results) +
  geom_boxplot(mapping = aes(x = year, y = std_resid, fill = year))
```

```{r}
# plot residual for each trim level
ggplot(data = results) +
  geom_boxplot(mapping = aes(x = trim, y = std_resid, fill = trim))
```